12:22:20 | ERROR | Error:
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
           │    └ <function MemoryObjectReceiveStream.receive_nowait at 0x7f27a354d870>
           └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
          └ <class 'anyio.WouldBlock'>

anyio.WouldBlock


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
                    │           └ <function MemoryObjectReceiveStream.receive at 0x7f27a354d900>
                    └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
          └ <class 'anyio.EndOfStream'>

anyio.EndOfStream


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               │     │   └ 3
               │     └ 9
               └ <function _main at 0x7f27a469e440>
  File "/usr/local/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
           │    │          └ 3
           │    └ <function BaseProcess._bootstrap at 0x7f27a48716c0>
           └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
    │    └ <function BaseProcess.run at 0x7f27a4870d30>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f27a46b21a0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...
    │    │        │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    │        │    └ ()
    │    │        └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
    │    └ <function subprocess_started at 0x7f27a3cd13f0>
    └ <SpawnProcess name='SpawnProcess-1' parent=1 started>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
    │              └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f27a46b2200>>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
           │       │   │    │             └ [<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8888)>]
           │       │   │    └ <function Server.serve at 0x7f27a3cd0700>
           │       │   └ <uvicorn.server.Server object at 0x7f27a46b2200>
           │       └ <function run at 0x7f27a46a96c0>
           └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object Server.serve at 0x7f27a2d12030>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f27a40dad40>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f27a40dacb0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f27a40dc820>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1899, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f27a46401f0>
    └ <Handle <TaskStepMethWrapper object at 0x7f27a1ebcb50>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f27a1ebcb50>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f27a1ebcb50>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f27a1ebcb50>()>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f27a30c4550>
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
                 │    └ <fastapi.applications.FastAPI object at 0x7f27a3d02320>
                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f27a30c4550>
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f27a30c6500>
          └ <fastapi.applications.FastAPI object at 0x7f27a3d02320>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f27a27e4310>
          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0x7f27a1355630>>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f27a30c4370>
          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f27a30c6500>
> File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 72, in __call__
    response = await self.dispatch_func(request, call_next)
                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f27a4871bd0>
                     │    │             └ <starlette.requests.Request object at 0x7f27a13550f0>
                     │    └ <function log_middle at 0x7f27a2d21b40>
                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f27a30c4370>

  File "/app/NBDapp/api_views.py", line 47, in log_middle
    response = await call_next(request)
                     │         └ <starlette.requests.Request object at 0x7f27a13550f0>
                     └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f27a4871bd0>

  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
          └ DoesNotExist('Object does not exist')
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
          │    │   │      │       │        │           └ <function MemoryObjectSendStream.send at 0x7f27a354e050>
          │    │   │      │       │        └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...
          │    │   │      │       └ <property object at 0x7f27a33bae30>
          │    │   │      └ <starlette.requests.Request object at 0x7f27a13550f0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f27a30c7310>
          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f27a30c4370>
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f27a280bc70>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f27a1e00dc0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f27a30c7880>
          └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f27a30c7310>
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f27a280bc70>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f27a1e00dc0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <fastapi.routing.APIRouter object at 0x7f27a3d01c30>
          └ <fastapi.middleware.asyncexitstack.AsyncExitStackMiddleware object at 0x7f27a30c7880>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
          │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f27a280bc70>
          │     │      │      └ <function set_body.<locals>.receive at 0x7f27a1e00dc0>
          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │     └ <function Route.handle at 0x7f27a320a680>
          └ <fastapi.routing.APIRoute object at 0x7f27a30a3df0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
          │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0x7f27a280bc70>
          │    │   │      └ <function set_body.<locals>.receive at 0x7f27a1e00dc0>
          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.1', 'server': ('192.168.0.4', 8888), '...
          │    └ <function request_response.<locals>.app at 0x7f27a2d23880>
          └ <fastapi.routing.APIRoute object at 0x7f27a30a3df0>
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
                     │    └ <starlette.requests.Request object at 0x7f27a1ebf160>
                     └ <function get_request_handler.<locals>.app at 0x7f27a2d237f0>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
                         └ <function run_endpoint_function at 0x7f27a3209480>
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
                 │         │      └ {'data': {'id': 5291981584, 'answer': 'Игры разума'}, 'response': <starlette.responses.Response object at 0x7f27a1d28c10>}
                 │         └ <function main_answer at 0x7f27a2d236d0>
                 └ <fastapi.dependencies.models.Dependant object at 0x7f27a30a2b30>

  File "/app/NBDapp/api_views.py", line 291, in main_answer
    question = await Question.get(id=session.curent_question)
                     │        │      │       └ 0
                     │        │      └ <Main_Session: 9110>
                     │        └ <classmethod(<function Model.get at 0x7f27a3055750>)>
                     └ <class 'DataBase.Models.Question'>

  File "/usr/local/lib/python3.10/site-packages/tortoise/queryset.py", line 1018, in _execute
    raise DoesNotExist("Object does not exist")
          └ <class 'tortoise.exceptions.DoesNotExist'>

tortoise.exceptions.DoesNotExist: Object does not exist
